<?php
// $Id: icontact_subscribe.install,v 1.1.6.2 2010/05/03 19:49:35 greenskin Exp $

/**
 * Implementation of hook_install().
 */
function icontact_subscribe_install() {
  
}

/**
 * Implementation of hook_uninstall().
 */
function icontact_subscribe_uninstall() {
  $variables = db_query("SELECT name FROM {variable} WHERE name LIKE 'icontact_subscribe%%'");
  while ($variable = db_fetch_object($variables)) {
    variable_del($variable->name);
  }
}
